#This is a sample hugo.toml configuration. You would package your own hugo.toml with your site.
baseURL = "https://yoursite[.]com"
title = "Your Site Name"
author = "You"

#Leave this section if you intend to use Arroz Con Dulce theme as your base theme.
[module]
  [[module.imports]]
    path = "github.com/sonofmartinus/arrozcondulce"

  [module.hugoVersion]
    extended = true  # Or false, depending on your needs
