name: hugo build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          path: arrozcondulce

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.1'
          # extended: true

      - name: Build
        working-directory: ./arrozcondulce/exampleSite
        run: |
         export HUGO_MODULE=github.com/sonofmartinus/arrozcondulce
         hugo --minify -t arrozcondulce

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./arrozcondulce/exampleSite/public
          cname: arrozcondulce.sonofmartinus.com
