name: hugo build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:

      - name: Debug
        run: |
         pwd
         ls -la
         echo "GitHub Workspace: $GITHUB_WORKSPACE"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/arrozcondulce
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        working-directory: ${{ github.workspace }}/arrozcondulce/exampleSite
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/arrozcondulce/exampleSite/public
          cname: arrozcondulce.sonofmartinus.com
